In [1]:
import sys
sys.path.append(r'reflutils')
from reflutils import REFL_COLUMN_NAMES
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [189]:
df = pd.read_csv(r'../.csv', index_col=0)

In [234]:
df[REFL_COLUMN_NAMES["stitch num"]] = 0
df[REFL_COLUMN_NAMES["catagory"]] = "i0"
df[REFL_COLUMN_NAMES["catagory"]].iloc[6:10] = 'overlap'
df[REFL_COLUMN_NAMES["catagory"]].iloc[10:] = "done"

In [235]:
df.adu = df.adu / df.Current

In [236]:
df

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory
0,249.9998,5.308,499.8265,8.5017,100.0,0.001,784774,83354,2.807628,0.0234,31.955812,0,i0
1,249.9998,5.308,499.7197,8.5006,100.0,0.001,791733,82581,2.839791,0.0234,31.955812,0,i0
2,249.9998,5.308,499.5244,8.5003,100.0,0.001,786375,82854,2.819445,0.0234,31.955812,0,i0
3,249.9979,5.308,500.0386,8.5001,100.0,0.001,784576,82703,2.807059,0.0234,31.955812,0,i0
4,250.0074,5.308,500.5376,8.5001,100.0,0.001,794600,82580,2.841965,0.0234,31.955812,0,i0
5,250.0112,5.308,500.3453,8.5001,100.0,0.001,793725,82833,2.839645,0.0234,31.955812,0,i0
6,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038,83066,1.822777,0.0245,31.955812,0,overlap
7,249.9998,5.770,500.2774,8.5001,100.0,0.001,362170,83298,1.114251,0.0255,31.955812,0,overlap
8,249.9960,6.000,500.1111,8.5001,100.0,0.001,250888,83046,0.671070,0.0265,31.955812,0,overlap
9,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141,82947,0.499585,0.0275,31.955812,0,overlap
10,249.9903,6.470,500.4117,8.5001,100.0,0.001,206323,83088,0.492129,0.0285,31.955812,0,done
11,249.9903,6.706,500.2156,8.5001,100.0,0.001,236151,82724,0.613179,0.0296,31.955812,0,done
12,249.9885,6.942,500.0294,8.5001,100.0,0.001,258369,82645,0.702813,0.0306,31.955812,0,done
13,250.0017,7.176,500.1111,8.5001,100.0,0.001,283307,83409,0.799237,0.0316,31.955812,0,done
14,250.0017,7.412,499.9875,8.5001,100.0,0.001,301864,82956,0.875676,0.0327,31.955812,0,done
15,250.0055,7.648,499.7884,8.5001,100.0,0.001,306130,83391,0.891711,0.0337,31.955812,0,done
16,250.0093,7.882,500.3133,8.5001,100.0,0.001,303317,82397,0.882574,0.0347,31.955812,0,done
17,250.0112,8.118,500.0867,8.5001,100.0,0.001,297291,82809,0.857631,0.0358,31.955812,0,done
18,250.0131,8.352,500.1851,8.5001,100.0,0.001,283829,82896,0.803137,0.0368,31.955812,0,done
19,249.9979,8.588,499.9936,8.5001,100.0,0.001,262104,82773,0.717342,0.0378,31.955812,0,done
20,249.9960,8.824,500.4018,8.5001,100.0,0.001,243313,82815,0.640961,0.0389,31.955812,0,done
21,249.9960,9.058,500.1820,8.5001,100.0,0.001,217573,82966,0.538036,0.0399,31.955812,0,done
22,249.9922,9.294,499.9913,8.5001,100.0,0.001,202324,83386,0.475769,0.0409,31.955812,0,done
23,249.9922,9.530,500.3392,8.5001,100.0,0.001,178704,82734,0.383360,0.0419,31.955812,0,done
24,249.9903,9.764,500.1508,8.5001,100.0,0.001,160400,82765,0.310353,0.0430,31.955812,0,done
25,249.9998,10.000,499.9677,8.5001,100.0,0.001,144030,82630,0.245632,0.0440,31.955812,0,done

In [243]:
i0 = df.where(df[REFL_COLUMN_NAMES["catagory"]] == "i0").dropna()
overlap = df.where(df[REFL_COLUMN_NAMES["catagory"]] == "overlap").dropna()
done = df.where(df[REFL_COLUMN_NAMES["catagory"]] == "done").dropna()

def weightedAverage(
    nominal: pd.Series | pd.DataFrame | np.ndarray,
    variance: pd.Series | pd.DataFrame | np.ndarray,
):
    """
    Computes the weighted average of a series of nominal points and their variance
    """

    weight = 1 / variance
    variance = 1 / weight.sum()
    average = (nominal * weight).sum() * variance

    return average, variance

def averageOfAbove(df: pd.DataFrame, label = "overlap"):
    """Adds a row to the dataframe with the averages of the columns"""
    averageDF = df.mean(numeric_only=True)
    averageDF[REFL_COLUMN_NAMES["catagory"]] = label
    return averageDF.to_frame().T

average = averageOfAbove(i0)
display(average)
display(overlap)
display(done)

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory
0,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory
6,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap
7,249.9998,5.770,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap
8,249.9960,6.000,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.671070,0.0265,31.955812,0.0,overlap
9,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory
10,249.9903,6.470,500.4117,8.5001,100.0,0.001,206323.0,83088.0,0.492129,0.0285,31.955812,0.0,done
11,249.9903,6.706,500.2156,8.5001,100.0,0.001,236151.0,82724.0,0.613179,0.0296,31.955812,0.0,done
12,249.9885,6.942,500.0294,8.5001,100.0,0.001,258369.0,82645.0,0.702813,0.0306,31.955812,0.0,done
13,250.0017,7.176,500.1111,8.5001,100.0,0.001,283307.0,83409.0,0.799237,0.0316,31.955812,0.0,done
14,250.0017,7.412,499.9875,8.5001,100.0,0.001,301864.0,82956.0,0.875676,0.0327,31.955812,0.0,done
15,250.0055,7.648,499.7884,8.5001,100.0,0.001,306130.0,83391.0,0.891711,0.0337,31.955812,0.0,done
16,250.0093,7.882,500.3133,8.5001,100.0,0.001,303317.0,82397.0,0.882574,0.0347,31.955812,0.0,done
17,250.0112,8.118,500.0867,8.5001,100.0,0.001,297291.0,82809.0,0.857631,0.0358,31.955812,0.0,done
18,250.0131,8.352,500.1851,8.5001,100.0,0.001,283829.0,82896.0,0.803137,0.0368,31.955812,0.0,done
19,249.9979,8.588,499.9936,8.5001,100.0,0.001,262104.0,82773.0,0.717342,0.0378,31.955812,0.0,done
20,249.9960,8.824,500.4018,8.5001,100.0,0.001,243313.0,82815.0,0.640961,0.0389,31.955812,0.0,done
21,249.9960,9.058,500.1820,8.5001,100.0,0.001,217573.0,82966.0,0.538036,0.0399,31.955812,0.0,done
22,249.9922,9.294,499.9913,8.5001,100.0,0.001,202324.0,83386.0,0.475769,0.0409,31.955812,0.0,done
23,249.9922,9.530,500.3392,8.5001,100.0,0.001,178704.0,82734.0,0.383360,0.0419,31.955812,0.0,done
24,249.9903,9.764,500.1508,8.5001,100.0,0.001,160400.0,82765.0,0.310353,0.0430,31.955812,0.0,done
25,249.9998,10.000,499.9677,8.5001,100.0,0.001,144030.0,82630.0,0.245632,0.0440,31.955812,0.0,done

In [245]:
overlap = pd.concat([average, overlap], ignore_index=True)
display(overlap)

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory
0,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap
1,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap
2,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap
3,249.9998,5.77,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap
4,249.996,6.0,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.67107,0.0265,31.955812,0.0,overlap
5,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap

In [239]:
from numpy import sqrt

priorDf = totalDf.where(totalDf[REFL_COLUMN_NAMES["catagory"]] != "i0").dropna().iloc[::-1]

priorOverlaps = priorDf.where(priorDf[REFL_COLUMN_NAMES["catagory"]] == "overlap").dropna().iloc[::-1]
currentOverlaps = totalDf.where(totalDf[REFL_COLUMN_NAMES["catagory"]] == "overlap").dropna()
priorOverlaps[REFL_COLUMN_NAMES["R"]] = priorOverlaps[REFL_COLUMN_NAMES["Raw"]]
priorOverlaps[REFL_COLUMN_NAMES["R Err"]] = priorOverlaps[REFL_COLUMN_NAMES["Raw"]]

priorOverlaps[REFL_COLUMN_NAMES["i0"]] = 1
priorOverlaps[REFL_COLUMN_NAMES["i0Err"]] = 0

In [240]:
display(priorOverlaps)
display(currentOverlaps)

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory,r,dr,i0,di0
6,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap,2.825922,2.825922,1,0
7,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap,1.822777,1.822777,1,0
8,249.9998,5.77,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap,1.114251,1.114251,1,0
9,249.996,6.0,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.67107,0.0265,31.955812,0.0,overlap,0.67107,0.67107,1,0
10,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap,0.499585,0.499585,1,0

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory
6,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap
7,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap
8,249.9998,5.77,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap
9,249.996,6.0,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.67107,0.0265,31.955812,0.0,overlap
10,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap

In [241]:
currentOverlaps[REFL_COLUMN_NAMES["i0"]] = priorOverlaps[REFL_COLUMN_NAMES["R"]] / currentOverlaps[REFL_COLUMN_NAMES["Raw"]]

scale = currentOverlaps[REFL_COLUMN_NAMES["i0"]].mean()
scaleVar = currentOverlaps[REFL_COLUMN_NAMES["i0"]].var()

display(currentOverlaps)
display(priorOverlaps)

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory,i0
6,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap,1.0
7,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap,1.0
8,249.9998,5.77,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap,1.0
9,249.996,6.0,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.67107,0.0265,31.955812,0.0,overlap,1.0
10,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap,1.0

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory,r,dr,i0,di0
6,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap,2.825922,2.825922,1,0
7,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap,1.822777,1.822777,1,0
8,249.9998,5.77,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap,1.114251,1.114251,1,0
9,249.996,6.0,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.67107,0.0265,31.955812,0.0,overlap,0.67107,0.67107,1,0
10,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap,0.499585,0.499585,1,0

In [242]:
currentOverlaps[REFL_COLUMN_NAMES["R"]] = currentOverlaps[REFL_COLUMN_NAMES["Raw"]] * scale
currentOverlaps[REFL_COLUMN_NAMES["R Err"]] = currentOverlaps[REFL_COLUMN_NAMES["R"]]**2 * (currentOverlaps[REFL_COLUMN_NAMES["Stat Update"]]**2 + scaleVar / scale**2)

averageR = (currentOverlaps[REFL_COLUMN_NAMES["R"]] + priorOverlaps[REFL_COLUMN_NAMES["R"]]) / 2
averageRErr = 1/(currentOverlaps[REFL_COLUMN_NAMES["R Err"]] + priorOverlaps[REFL_COLUMN_NAMES["R Err"]])

averageDF = pd.DataFrame({REFL_COLUMN_NAMES["R"]: averageR, REFL_COLUMN_NAMES["R Err"]: averageRErr, REFL_COLUMN_NAMES["catagory"]: "done"})

display(pd.concat([currentOverlaps, averageDF], ignore_index=True))

,Energy,Theta,Current,HOS,POL,Exposure,int,bg,adu,q,stat_update,stitch_num,catagory,i0,r,dr
0,250.00265,5.308,499.998683,8.500483,100.0,0.001,789297.166667,82817.5,2.825922,0.0234,31.955812,0.0,overlap,1.0,2.825922,8154.927451
1,250.0131,5.538,500.1523,8.5001,100.0,0.001,539038.0,83066.0,1.822777,0.0245,31.955812,0.0,overlap,1.0,1.822777,3392.868169
2,249.9998,5.77,500.2774,8.5001,100.0,0.001,362170.0,83298.0,1.114251,0.0255,31.955812,0.0,overlap,1.0,1.114251,1267.844536
3,249.996,6.0,500.1111,8.5001,100.0,0.001,250888.0,83046.0,0.67107,0.0265,31.955812,0.0,overlap,1.0,0.67107,459.869952
4,249.9941,6.236,500.5956,8.5001,100.0,0.001,208141.0,82947.0,0.499585,0.0275,31.955812,0.0,overlap,1.0,0.499585,254.869951
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,done,NaN,2.825922,0.000123
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,done,NaN,1.822777,0.000295
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,done,NaN,1.114251,0.000788
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,done,NaN,0.67107,0.002171
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,done,NaN,0.499585,0.003916