In [1]:
import sys
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import warnings
import pandas as pd
warnings.filterwarnings('ignore')
import numpy as np

import pandas as pd
import seaborn as sns
sys.path.append(r'reflutils')
from reflutils import FileDialog, Refl, tree

In [4]:
test_xrr = Refl()

ValueError: operands could not be broadcast together with shapes (2,) (0,)

In [4]:
test_xrr.display()

In [5]:
test_xrr.refl

,Energy,Theta,Current,HOS,POL,Exposure,Intensity,Background,RawRefl,Refl,Err,Q,chi,k,lam,lamErr
0,283.7122,0.208,500.4590,10.2000,100.0,0.001,175006.0,82802.0,92204.0,0.759934,1.122403e-03,0.0010,1,179.076797,2.424406e+02,8.077047e-02
1,283.7122,0.416,500.2843,10.2000,100.0,0.001,137086.0,82216.0,54870.0,0.452390,6.682098e-04,0.0021,1,179.076797,2.424406e+02,8.077047e-02
2,283.7195,0.624,500.0966,10.2000,100.0,0.001,127312.0,82106.0,45206.0,0.372852,5.508936e-04,0.0031,1,179.076797,2.424406e+02,8.077047e-02
3,283.7000,0.834,500.5742,10.2000,100.0,0.001,113738.0,82480.0,31258.0,0.257565,3.801519e-04,0.0042,1,179.076797,2.424406e+02,8.077047e-02
4,283.7000,1.042,500.3964,10.2000,100.0,0.001,109672.0,82150.0,27522.0,0.226861,3.349439e-04,0.0052,1,179.076797,2.424406e+02,8.077047e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,283.7000,65.652,500.0600,6.5002,100.0,10.000,173664.0,82662.0,91002.0,0.000002,1.670307e-15,0.2619,1,29.563558,8.770745e+07,4.855176e+11
145,283.7000,66.522,499.8502,6.5002,100.0,10.000,166376.0,83339.0,83037.0,0.000002,1.503673e-15,0.2637,1,29.563558,8.770745e+07,4.855176e+11
146,283.7000,67.392,499.8753,6.5002,100.0,10.000,158877.0,83160.0,75717.0,0.000002,1.352783e-15,0.2654,1,29.563558,8.770745e+07,4.855176e+11
147,283.7000,68.260,499.6564,6.5002,100.0,10.000,155136.0,83028.0,72108.0,0.000002,1.280880e-15,0.2671,1,29.563558,8.770745e+07,4.855176e+11
148,283.7000,69.130,499.1917,6.5002,100.0,10.000,157106.0,82815.0,74291.0,0.000002,1.327455e-15,0.2686,1,29.563558,8.770745e+07,4.855176e+11

In [8]:
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import matplotlib.colors as mcolors
import seaborn as sns
import plotly.express as px

def widget(obj: Refl, q):
    images = obj.images.loc[obj.images["Q"] == q]
    point = obj.refl.loc[obj.refl["Q"] == q]
    rows = 4
    cols = 2 * len(images)

    imin = min([image.min() for image in images["Masked"]])
    imax = max([image.max() for image in images["Masked"]])

    fig = plt.figure(figsize=(12, 6))
    gs = GridSpec(rows, cols, figure=fig, wspace=0, hspace=0.1) 

    norm = mcolors.Normalize(vmin=imin, vmax=imax)

    for i, image in enumerate(images["Masked"]):
        masked = fig.add_subplot(gs[0, 2*i], xticks=[], yticks=[])

        masked.imshow(image, norm=norm, cmap="coolwarm")

        filter = fig.add_subplot(gs[0, 2*i+1], xticks=[], yticks=[])
        filter.imshow(images["Filtered"].iloc[i], norm=norm, cmap="coolwarm")

        beam = fig.add_subplot(gs[1, 2*i], xticks=[], yticks=[])
        beam.imshow(images["Beam"].iloc[i], norm=norm, cmap="coolwarm")

        dark = fig.add_subplot(gs[1, 2*i+1], xticks=[], yticks=[])
        dark.imshow(images["Dark"].iloc[i], norm=norm, cmap="coolwarm")

    colors = plt.cm.ScalarMappable(norm=norm, cmap="coolwarm")
    color_values = colors.to_rgba(obj.refl["RawRefl"])

    refl = fig.add_subplot(gs[2:, :])
    refl.set_yscale("log")
    obj.plot(ax=refl, color=color_values, marker="o", label="Raw Reflectivity")
    
    refl.scatter(x = point["Q"], y = point["Refl"], color="black", marker="o", label="Selected Point")
    refl.set_ylabel("Reflectivity")
    refl.legend()

    cax = fig.add_axes([.93, 0.15, 0.02, 0.7])
    cb = plt.colorbar(plt.cm.ScalarMappable(norm=norm, cmap="coolwarm"), cax=cax, format="%.0e")
    if len(point)> 0:
        new_point = point.copy()
        new_point["Beam Spot"] = images["Beam Spots"].reset_index(drop=True)
        new_point["Dark Spot"] = images["Dark Spots"].reset_index(drop=True)
        display(new_point)
    else:
        I0 = obj.refl["lam"].iloc[0]
        I0_err = obj.refl["lamErr"].iloc[0]
        print(f"I0 =  {I0:.2e} +/- {I0_err:.2e}")
        display(images[["Beam Spots", "Dark Spots"]].reset_index(drop=True).T)


    plt.show()

In [13]:
from ipywidgets import interact, SelectionSlider, fixed
%matplotlib widget

q = test_xrr.refl["Q"]
q_vals =[0 if i == 0 else q.iloc[i] for i in range(len(q))]

interact(widget, obj=fixed(test_xrr), q = SelectionSlider(options=q_vals, value=q_vals[0], description="Q", continuous_update=False))

interactive(children=(SelectionSlider(continuous_update=False, description='Q', options=(0, 0.0021, 0.0031, 0.…

In [30]:
import pandas as pd
from bokeh.io import push_notebook, show, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import BoxSelectTool, HoverTool


output_notebook()

pd.set_option('plotting.backend', 'pandas_bokeh')

TOOLS = [
    HoverTool(
    tooltips=[
        ( 'date',   '@date{%F}'            ),
        ( 'Refl',  '@{RawRefl}{0.2f}' ), # use @{ } for field names with spaces
        ( 'volume', '@volume{0.00 a}'      ),
    ],

    formatters={
        '@date'        : 'datetime', # use 'datetime' formatter for '@date' field
        '@{adj close}' : 'printf',   # use 'printf' formatter for '@{adj close}' field
                                     # use default 'numeral' formatter for other fields
    },

    mode='vline'
), 
    'crosshair']

p = figure(title="Reflectivity", tools=TOOLS, plot_width=900, plot_height=500, x_axis_label="Q", y_axis_label="Reflectivity", y_axis_type="log")
p.circle(x="Q", y="Refl", source=test_xrr.refl)
show(p)

In [ ]:
# Compile a list of data points that are suspect
# Make slides / mini reports for each of these points
# should we allways delete these points? or what happened experimentally?

# Save the csv and the images outside of the fits files

In [3]:
import pandas as pd

df = pd.DataFrame({
    "A": [1,2,3,4,5],
    "B": [6,7,8,9,10]
})
display(df)

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [16]:
df.describe

<bound method NDFrame.describe of    A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10>